version: 2.1

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - ${CACHE_VER}-dependencies-{{ checksum "application/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - ${CACHE_VER}-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devops
            . ~/.devops/bin/activate
            cd application
            make install
      - save_cache:
          paths:
            - ~/.devops
          key: ${CACHE_VER}-dependencies-{{ checksum "application/requirements.txt" }}
      - run:
          name: run lint
          command: |
            . ~/.devops/bin/activate
            cd application
            make lint
